# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 14ae4988346de50a78726fc734066ce7d269935ec474fcb1b6593a6d8ab7180b0c4f5300369af0eabb98e202926e37e4916042e38e114b2c3c1996e9fd29aa61

test:
  secret_key_base: e13f91293ff6dccd164ef59a3a8342195ee9df560af048759aac8d6b6a90474fb818307716307f5a36e7e7204183ae6622b31834ca117df88caf4f0d8340ae2a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
